In [1]:
import numpy as np

In [29]:
from sklearn.datasets import load_iris
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
x = iris.data

In [7]:
y = iris.target

In [8]:
y.shape

(150,)

In [9]:
# One hot encoding
# class 0 --> [1,0,0]
# class 0 --> [0,1,0]
# class 0 --> [0,0,1]
y = to_categorical(y)

In [10]:
y.shape

(150, 3)

In [11]:
# Separando o dataset em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.33, random_state=42)

In [12]:
# Padronizando os dados
scaler_object = MinMaxScaler()

In [13]:
scaler_object.fit(X_train)

MinMaxScaler()

In [20]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_train

array([[0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ],
       [0.58823529, 0.31818182, 0.67857143, 0.70833333],
       [0.14705882, 0.63636364, 0.14285714, 0.04166667],
       [0.20588235, 0.45454545, 0.08928571, 0.04166667],
       [0.23529412, 0.59090909, 0.10714286, 0.16666667],
       [0.38235294, 0.31818182, 0.55357143, 0.5       ],
       [0.23529412, 0.63636364, 0.07142857, 0.04166667],
       [0.41176471, 0.45454545, 0.55357143, 0.45833333],
       [1.        , 0.81818182,

In [19]:
scaled_X_test = scaler_object.transform(X_test)
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [25]:
# construindo o modelo
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', 
              optimizer='adam',
              metrics=['accuracy'])

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

Epoch 1/150
4/4 - 0s - loss: 1.0335 - accuracy: 0.6600 - 366ms/epoch - 92ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0238 - accuracy: 0.6600 - 5ms/epoch - 1ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0142 - accuracy: 0.6600 - 4ms/epoch - 1ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0059 - accuracy: 0.6600 - 4ms/epoch - 984us/step
Epoch 5/150
4/4 - 0s - loss: 0.9969 - accuracy: 0.6600 - 4ms/epoch - 1ms/step
Epoch 6/150
4/4 - 0s - loss: 0.9892 - accuracy: 0.6600 - 5ms/epoch - 1ms/step
Epoch 7/150
4/4 - 0s - loss: 0.9811 - accuracy: 0.6600 - 4ms/epoch - 1ms/step
Epoch 8/150
4/4 - 0s - loss: 0.9732 - accuracy: 0.6600 - 6ms/epoch - 1ms/step
Epoch 9/150
4/4 - 0s - loss: 0.9652 - accuracy: 0.6600 - 5ms/epoch - 1ms/step
Epoch 10/150
4/4 - 0s - loss: 0.9576 - accuracy: 0.6600 - 6ms/epoch - 2ms/step
Epoch 11/150
4/4 - 0s - loss: 0.9506 - accuracy: 0.6600 - 5ms/epoch - 1ms/step
Epoch 12/150
4/4 - 0s - loss: 0.9433 - accuracy: 0.6600 - 5ms/epoch - 1ms/step
Epoch 13/150
4/4 - 0s - loss: 0.9362 - accuracy: 0.6600 

In [32]:
predictions = model.predict(scaled_X_test) 
classes=np.argmax(predictions,axis=1)

2/2 [==============================] - 0s 2ms/step


In [33]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [35]:
confusion_matrix(y_test.argmax(axis=1),classes)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]])

In [36]:
print(classification_report(y_test.argmax(axis=1),classes))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [37]:
accuracy_score(y_test.argmax(axis=1),classes)

0.96