In [99]:
import spacy as sp
import en_core_web_sm
import numpy as np
import random
from keras.preprocessing.text import Tokenizer
from keras_preprocessing.sequence import pad_sequences
from keras.utils import to_categorical 
from keras.models import Sequential 
from keras.layers import Dense, LSTM, Embedding
from pickle import dump, load

In [2]:
#Função de leitura de arquivo de texto
def read_file(filepath):
    with open (filepath) as f:
        str_text = f.read()
        return str_text

In [3]:
#Função de limpeza do texto
#Tira do texto pontuação, novas linhas e caracteres especiais
def separate_punc(doc_text):
    return[token.text.lower() 
           for token in nlp(doc_text) 
           if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ' ]

In [4]:
#Próximo passo torkenizar e limpar o texto
nlp = sp.load('en_core_web_sm', disable=['parser', 'tagger', 'ner','lemmatizer'])

In [5]:
nlp.max_length = 1198623

In [6]:
d = read_file('/Users/iaquine/Documents/GitHub/Natural-language-processing-NLP/Data/melville-moby_dick.txt')

In [7]:
tokens = separate_punc(d)

In [8]:
type(tokens)

list

In [9]:
len(tokens)

214708

In [10]:
#Predição da proxima palavra
train_len = 25+1 

text_sequences = []

for i in range(train_len, len(tokens)):
    
   
    seq = tokens[i-train_len:i]
    
    
    text_sequences.append(seq)

In [11]:
text_sequences[13]

['precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and']

In [12]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

In [13]:
' '.join(text_sequences[1])

'1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest'

In [14]:
' '.join(text_sequences[2])

'loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me'

In [15]:
#Convertendo os tokens em um sistema númerico
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)

In [16]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [17]:
sequences[0]

[158,
 9443,
 17526,
 402,
 42,
 1043,
 43,
 247,
 659,
 140,
 296,
 116,
 82,
 787,
 347,
 113,
 36,
 50,
 1788,
 6,
 49,
 3028,
 3,
 218,
 442,
 5]

In [18]:
tokenizer.index_word

{1: 'the',
 2: 'of',
 3: 'and',
 4: 'a',
 5: 'to',
 6: 'in',
 7: 'that',
 8: 'his',
 9: 'it',
 10: 'i',
 11: 'he',
 12: 'but',
 13: "'s",
 14: 'as',
 15: 'with',
 16: 'is',
 17: 'was',
 18: 'for',
 19: 'all',
 20: 'this',
 21: 'at',
 22: 'not',
 23: 'by',
 24: 'whale',
 25: 'from',
 26: 'so',
 27: 'him',
 28: 'on',
 29: 'be',
 30: 'one',
 31: 'you',
 32: 'there',
 33: 'now',
 34: 'had',
 35: 'have',
 36: 'or',
 37: 'were',
 38: 'they',
 39: 'like',
 40: 'which',
 41: 'then',
 42: 'me',
 43: 'some',
 44: 'their',
 45: 'what',
 46: 'when',
 47: 'an',
 48: 'are',
 49: 'my',
 50: 'no',
 51: 'upon',
 52: 'out',
 53: 'man',
 54: 'into',
 55: 'ship',
 56: 'up',
 57: 'more',
 58: 'ahab',
 59: 'if',
 60: 'them',
 61: 'old',
 62: 'we',
 63: 'sea',
 64: 'would',
 65: "'",
 66: 'ye',
 67: 'do',
 68: 'other',
 69: 'been',
 70: 'over',
 71: 'these',
 72: 'will',
 73: 'though',
 74: 'only',
 75: 'its',
 76: 'down',
 77: 'such',
 78: 'who',
 79: 'yet',
 80: 'head',
 81: 'time',
 82: 'long',
 83: 'boat

In [19]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

158 : chapter
9443 : 1
17526 : loomings
402 : call
42 : me
1043 : ishmael
43 : some
247 : years
659 : ago
140 : never
296 : mind
116 : how
82 : long
787 : precisely
347 : having
113 : little
36 : or
50 : no
1788 : money
6 : in
49 : my
3028 : purse
3 : and
218 : nothing
442 : particular
5 : to


In [20]:
tokenizer.word_counts

OrderedDict([('chapter', 4447),
             ('1', 28),
             ('loomings', 3),
             ('call', 1382),
             ('me', 16095),
             ('ishmael', 500),
             ('some', 15789),
             ('years', 2400),
             ('ago', 815),
             ('never', 5262),
             ('mind', 2039),
             ('how', 6330),
             ('long', 8567),
             ('precisely', 690),
             ('having', 1679),
             ('little', 6412),
             ('or', 17879),
             ('no', 14916),
             ('money', 305),
             ('in', 105799),
             ('my', 15231),
             ('purse', 178),
             ('and', 164029),
             ('nothing', 2936),
             ('particular', 1273),
             ('to', 117832),
             ('interest', 442),
             ('on', 26910),
             ('shore', 572),
             ('i', 53430),
             ('thought', 3874),
             ('would', 11232),
             ('sail', 2522),
             ('about', 

In [21]:
#Contando palavras únicas
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

17526

In [22]:
seq_matrix = np.array(sequences)
seq_matrix

array([[  158,  9443, 17526, ...,   218,   442,     5],
       [ 9443, 17526,   402, ...,   442,     5,  1165],
       [17526,   402,    42, ...,     5,  1165,    42],
       ...,
       [  240,   938,   351, ...,  1419,  1313,    74],
       [  938,   351,  1418, ...,  1313,    74,   219],
       [  351,  1418,     3, ...,    74,   219,   222]])

In [23]:
x_features = seq_matrix[:,:-1]
x_features

array([[  158,  9443, 17526, ...,     3,   218,   442],
       [ 9443, 17526,   402, ...,   218,   442,     5],
       [17526,   402,    42, ...,   442,     5,  1165],
       ...,
       [  240,   938,   351, ...,    84,  1419,  1313],
       [  938,   351,  1418, ...,  1419,  1313,    74],
       [  351,  1418,     3, ...,  1313,    74,   219]])

In [24]:
y_labels = seq_matrix[:,-1]
y_labels

array([   5, 1165,   42, ...,   74,  219,  222])

In [25]:
y_labels = to_categorical(y_labels,num_classes=vocabulary_size+1)
y_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [26]:
x_features.shape

(214682, 25)

In [51]:
seq_len = x_features[1]
seq_len

array([ 9443, 17526,   402,    42,  1043,    43,   247,   659,   140,
         296,   116,    82,   787,   347,   113,    36,    50,  1788,
           6,    49,  3028,     3,   218,   442,     5])

In [52]:
seq_len.size

25

In [53]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, seq_len.size, input_length = seq_len.size))
    model.add(LSTM(50,return_sequences=True))
    model.add(LSTM(50))
    model.add(Dense(50,activation='relu'))
    
    model.add(Dense(vocabulary_size,activation = 'softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    model.summary()
    
    return model

In [54]:
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 25, 25)            438175    
                                                                 
 lstm_6 (LSTM)               (None, 25, 50)            15200     
                                                                 
 lstm_7 (LSTM)               (None, 50)                20200     
                                                                 
 dense_6 (Dense)             (None, 50)                2550      
                                                                 
 dense_7 (Dense)             (None, 17527)             893877    
                                                                 
Total params: 1,370,002
Trainable params: 1,370,002
Non-trainable params: 0
_________________________________________________________________


In [58]:
model.fit(x_features,y_labels,batch_size=128,epochs=100,verbose=1)

Epoch 1/100
1678/1678 [==============================] - 104s 62ms/step - loss: 5.3031 - accuracy: 0.1349
Epoch 2/100
1678/1678 [==============================] - 101s 60ms/step - loss: 5.2642 - accuracy: 0.1365
Epoch 3/100
1678/1678 [==============================] - 101s 60ms/step - loss: 5.2257 - accuracy: 0.1378
Epoch 4/100
1678/1678 [==============================] - 101s 60ms/step - loss: 5.1910 - accuracy: 0.1387
Epoch 5/100
1678/1678 [==============================] - 109s 65ms/step - loss: 5.1580 - accuracy: 0.1404
Epoch 6/100
1678/1678 [==============================] - 115s 68ms/step - loss: 5.1271 - accuracy: 0.1416
Epoch 7/100
1678/1678 [==============================] - 118s 71ms/step - loss: 5.0965 - accuracy: 0.1430
Epoch 8/100
1678/1678 [==============================] - 123s 73ms/step - loss: 5.0688 - accuracy: 0.1444
Epoch 9/100
1678/1678 [==============================] - 125s 74ms/step - loss: 5.0423 - accuracy: 0.1456
Epoch 10/100
1678/1678 [======================

In [60]:
model.save('mymobidick_model.h5')

In [61]:
dump(tokenizer,open('my_simpletokenizer','wb'))

In [111]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    
    output_text = []
    
    input_text = seed_text
    
    for i in range(num_gen_words):
        
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len.size, truncating='pre')
        
        pred_word_ind = model.predict(pad_encoded, verbose=0)[0]
        classes=np.argmax(pred_word_ind)
        
        pred_word = tokenizer.index_word[classes] 
        
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    return ' '.join(output_text)

In [68]:
# gerando o texto seed
random.seed(101)
random_pick = random.randint(0,len(text_sequences))
random_seed_text = text_sequences[random_pick]
random_seed_text

['he',
 'recognised',
 'his',
 'cutting',
 'spade',
 'pole',
 'entangled',
 'in',
 'the',
 'lines',
 'that',
 'were',
 'knotted',
 'round',
 'the',
 'tail',
 'of',
 'one',
 'of',
 'these',
 'whales',
 'there',
 "'s",
 'a',
 'pretty',
 'fellow']

In [70]:
seed_text = ' '.join(random_seed_text)
seed_text

"he recognised his cutting spade pole entangled in the lines that were knotted round the tail of one of these whales there 's a pretty fellow"

In [113]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=1000)

"'s eyes and here were insular seeing the whale boat once;--seen in the whale 's belly and wards is the whale 's company and then handing the ship in the sea and the whale was traced and throughout a little duty to be slapped by a whale 's head that 's a man was no to the sails;--malays would choke me to be doubted that to be the whale is not to be the whale is not to be accommodated with a few minutes awaited him in a whale 's head and then the captain is traced and pray that a little respond to the sperm whale 's head contrasted view of that stroke me flaked them!--scrape the whale useless dante and fell rudimental resemblance to his own unbiased steadfast man the veriest trifles capriciously daring dames are sallied up and ranges from a whale 's head that is walking down the deck and then as the whale 's head were no more to grieve that the whale is not to be the whale is a little frisky though the whale is stranded up in the sea and the only jamming jeopardy of the whale 's side an